import type { Snapshot } from "./types"

/** Rich mock covering every state/detail — for design review (bun run smoke). */
export const mockSnapshot: Snapshot = {
  time: "thu · 14:08",
  agents: [
    {
      id: "web-auth-01",
      pid: 74867,
      kind: "claude",
      procs: 1,
      project: "webapp",
      cwd: "/Users/zee/Code/webapp",
      branch: "fix/auth-redirect",
      model: "opus-4.8 1m",
      status: "waiting",
      question: "Should I overwrite the existing config at app/config.ts, or merge the new keys into it?",
      lastActivity: "AskUserQuestion",
      recent: ["✓ bun test → 42 pass", "edit app/config.ts", "read app/config.ts"],
      contextPct: 96,
      costUsd: 3.9,
      tokens: 192_000,
      uptimeSec: 41 * 60,
      idleSec: 8 * 60,
    },
    {
      id: "zee-main-02",
      pid: 21121,
      kind: "claude",
      procs: 1,
      project: "zefleet",
      cwd: "/Users/zee/Code/zefleet",
      branch: "main",
      model: "opus-4.8",
      status: "working",
      lastActivity: "edit components/AgentBlock.tsx",
      recent: ["edit components/AgentBlock.tsx", "run bun run typecheck", "read theme.ts"],
      contextPct: 71,
      costUsd: 1.24,
      tokens: 64_300,
      uptimeSec: 12 * 60,
      idleSec: 3,
    },
    {
      id: "api-rate-03",
      pid: 50412,
      kind: "claude",
      procs: 1,
      project: "api-gateway",
      cwd: "/Users/zee/Code/api-gateway",
      branch: "feat/rate-limit",
      model: "sonnet-4.6",
      status: "working",
      lastActivity: "run bun test src/limiter.test.ts",
      recent: ["run bun test src/limiter.test.ts", "edit src/limiter.ts", "grep tokenBucket"],
      contextPct: 38,
      costUsd: 0.88,
      tokens: 41_200,
      uptimeSec: 22 * 60,
      idleSec: 11,
    },
    {
      id: "infra-deploy-04",
      pid: 60233,
      kind: "codex",
      procs: 1,
      project: "infra",
      cwd: "/Users/zee/Code/infra",
      branch: "deploy/staging",
      model: "gpt-5.5",
      status: "working",
      lastActivity: "apply_patch terraform/staging.tf",
      recent: ["apply_patch terraform/staging.tf", "exec terraform plan"],
      contextPct: 22,
      costUsd: 0.12,
      tokens: 138_800,
      uptimeSec: 40 * 60,
      idleSec: 7,
    },
    {
      id: "legacy-hotfix-05",
      pid: 41980,
      kind: "claude",
      procs: 1,
      project: "legacy-svc",
      cwd: "/Users/zee/Code/legacy-svc",
      branch: "hotfix/npe",
      model: "sonnet-4.6",
      status: "error",
      lastActivity: "✕ bun test → 3 failed",
      recent: ["✕ bun test → 3 failed", "edit src/handler.ts"],
      contextPct: 54,
      costUsd: 0.67,
      tokens: 52_900,
      uptimeSec: 9 * 60,
      idleSec: 90,
    },
    {
      id: "docs-idle-06",
      pid: 33110,
      kind: "claude",
      procs: 1,
      project: "docs-site",
      cwd: "/Users/zee/Code/docs-site",
      branch: "main",
      model: "haiku-4.5",
      status: "idle",
      lastActivity: "wrote getting-started.mdx",
      recent: ["wrote getting-started.mdx"],
      contextPct: 12,
      costUsd: 0.04,
      tokens: 9_400,
      uptimeSec: 75 * 60,
      idleSec: 18 * 60,
    },
  ],
  servers: [
    { port: 3000, pid: 74867, memKB: 14 * 1024 * 1024, uptime: "41m", project: "webapp", branch: "fix/auth-redirect", stale: false },
    { port: 5173, pid: 33110, memKB: 2.1 * 1024 * 1024, uptime: "75m", project: "docs-site", branch: "main", stale: false },
    { port: 8787, pid: 50412, memKB: 0.9 * 1024 * 1024, uptime: "22m", project: "api-gateway", branch: "feat/rate-limit", stale: true },
  ],
  worktrees: [
    { repo: "omnipair-webapp", total: 9, changed: 5 },
    { repo: "webapp", total: 4, changed: 1 },
    { repo: "argo", total: 7, changed: 0 },
  ],
}
