import type { Snapshot } from "./types"

/** Rich mock covering every state/detail — for design review (bun run smoke). */
export const mockSnapshot: Snapshot = {
  time: "thu · 14:08",
  agents: [
    {
      id: "web-auth-01",
      pid: 74867,
      kind: "claude",
      project: "webapp",
      wt: "fix-auth",
      cwd: "/Users/zee/Code/webapp/.claude/worktrees/fix-auth",
      branch: "fix/auth-redirect",
      model: "opus-4.8 1m",
      status: "waiting",
      waitKind: "question",
      question: "Should I overwrite the existing config at app/config.ts, or merge the new keys into it?",
      options: ["Overwrite", "Merge keys"],
      procs: 1,
      lastActivity: "AskUserQuestion",
      recent: ["✓ bun test → 42 pass", "edit app/config.ts", "read app/config.ts"],
      contextPct: 96,
      costUsd: 3.9,
      tokens: 192_000,
      uptimeSec: 41 * 60,
      idleSec: 8 * 60,
    },
    {
      id: "omni-tf-02",
      pid: 81244,
      kind: "claude",
      project: "omnipair",
      wt: "agent-3",
      cwd: "/Users/zee/Code/omnipair/.claude/worktrees/agent-3",
      branch: "infra/staging",
      model: "opus-4.8",
      status: "waiting",
      waitKind: "approval",
      question: "run terraform apply -auto-approve",
      procs: 1,
      lastActivity: "run terraform apply -auto-approve",
      recent: ["run terraform plan", "edit staging.tf"],
      contextPct: 44,
      costUsd: 1.02,
      tokens: 88_000,
      uptimeSec: 65 * 60,
      idleSec: 4 * 60,
    },
    {
      id: "zee-main-03",
      pid: 21121,
      kind: "claude",
      project: "zefleet",
      cwd: "/Users/zee/Code/zefleet",
      branch: "main",
      model: "opus-4.8",
      status: "working",
      procs: 2,
      lastActivity: "edit components/AgentBlock.tsx",
      recent: ["edit components/AgentBlock.tsx", "run bun run typecheck", "read theme.ts"],
      contextPct: 71,
      costUsd: 1.24,
      burnPerHour: 5.2,
      diff: { files: 4, plus: 86, minus: 12 },
      tokens: 64_300,
      uptimeSec: 12 * 60,
      idleSec: 3,
    },
    {
      id: "api-rate-04",
      pid: 50412,
      kind: "claude",
      project: "api-gateway",
      cwd: "/Users/zee/Code/api-gateway",
      branch: "feat/rate-limit",
      model: "sonnet-4.6",
      status: "working",
      procs: 1,
      lastActivity: "run bun test src/limiter.test.ts",
      recent: ["run bun test src/limiter.test.ts", "edit src/limiter.ts", "grep tokenBucket"],
      contextPct: 38,
      ctxGhostPct: 88,
      costUsd: 0.88,
      burnPerHour: 2.1,
      tokens: 41_200,
      uptimeSec: 22 * 60,
      idleSec: 11,
    },
    {
      id: "docs-ready-05",
      pid: 33110,
      kind: "claude",
      project: "docs-site",
      cwd: "/Users/zee/Code/docs-site",
      branch: "main",
      model: "haiku-4.5",
      status: "ready",
      procs: 1,
      lastActivity: "wrote getting-started.mdx",
      recent: ["wrote getting-started.mdx", "✓ bun run build → ok"],
      contextPct: 12,
      costUsd: 0.04,
      diff: { files: 9, plus: 214, minus: 38 },
      tokens: 9_400,
      uptimeSec: 75 * 60,
      idleSec: 3 * 60,
    },
    {
      id: "legacy-err-06",
      pid: 41980,
      kind: "claude",
      project: "legacy-svc",
      cwd: "/Users/zee/Code/legacy-svc",
      branch: "hotfix/npe",
      model: "sonnet-4.6",
      status: "error",
      question: "turn ended on a failed tool call",
      procs: 1,
      lastActivity: "✕ bun test → 3 failed",
      recent: ["✕ bun test → 3 failed", "edit src/handler.ts"],
      contextPct: 54,
      costUsd: 0.67,
      tokens: 52_900,
      uptimeSec: 9 * 60,
      idleSec: 90,
    },
    {
      id: "infra-codex-07",
      pid: 60233,
      kind: "codex",
      project: "infra",
      cwd: "/Users/zee/Code/infra",
      branch: "deploy/staging",
      model: "gpt-5.5",
      status: "unknown",
      procs: 1,
      lastActivity: "transcript not parsed yet",
      recent: [],
      contextPct: 0,
      costUsd: 0,
      tokens: 0,
      uptimeSec: 40 * 60,
      idleSec: 0,
    },
    {
      id: "play-idle-08",
      pid: 39001,
      kind: "claude",
      project: "playground",
      cwd: "/Users/zee/Code/playground",
      branch: "main",
      model: "haiku-4.5",
      status: "idle",
      procs: 1,
      lastActivity: "explained the regex",
      recent: ["explained the regex"],
      contextPct: 6,
      costUsd: 0.01,
      tokens: 3_100,
      uptimeSec: 3 * 3600,
      idleSec: 52 * 60,
    },
  ],
  servers: [
    {
      port: 3000,
      pid: 74867,
      memKB: 14 * 1024 * 1024,
      uptime: "41m",
      project: "webapp",
      branch: "fix/auth-redirect",
      cwd: "/Users/zee/Code/webapp",
      stale: false,
    },
    {
      port: 5173,
      pid: 33110,
      memKB: 2.1 * 1024 * 1024,
      uptime: "75m",
      project: "docs-site",
      branch: "main",
      cwd: "/Users/zee/Code/docs-site",
      stale: false,
    },
    {
      port: 8787,
      pid: 50412,
      memKB: 0.9 * 1024 * 1024,
      uptime: "22m",
      project: "api-gateway",
      branch: "feat/rate-limit",
      cwd: "/Users/zee/Code/api-gateway/.claude/worktrees/gone",
      stale: true,
    },
  ],
  worktrees: [
    {
      repo: "omnipair-webapp",
      path: "/Users/zee/Code/omnipair-webapp",
      total: 3,
      changed: 2,
      items: [
        {
          name: "feat-pairing",
          branch: "feat/pairing",
          dirty: 12,
          ageDays: 1,
          path: "/Users/zee/Code/omnipair-webapp/.claude/worktrees/feat-pairing",
        },
        {
          name: "fix-ws-leak",
          branch: "fix/ws-leak",
          dirty: 3,
          ageDays: 4,
          path: "/Users/zee/Code/omnipair-webapp/.claude/worktrees/fix-ws-leak",
        },
        {
          name: "agent-7",
          branch: "agent-7",
          dirty: 0,
          ageDays: 19,
          path: "/Users/zee/Code/omnipair-webapp/.claude/worktrees/agent-7",
        },
      ],
    },
    {
      repo: "webapp",
      path: "/Users/zee/Code/webapp",
      total: 2,
      changed: 1,
      items: [
        {
          name: "fix-auth",
          branch: "fix/auth-redirect",
          dirty: 5,
          ageDays: 0,
          path: "/Users/zee/Code/webapp/.claude/worktrees/fix-auth",
        },
        {
          name: "spike-otel",
          branch: "spike/otel",
          dirty: 0,
          ageDays: 11,
          path: "/Users/zee/Code/webapp/.claude/worktrees/spike-otel",
        },
      ],
    },
    {
      repo: "argo",
      path: "/Users/zee/Code/argo",
      total: 2,
      changed: 0,
      items: [
        {
          name: "agent-2",
          branch: "agent-2",
          dirty: 0,
          ageDays: 23,
          path: "/Users/zee/Code/argo/.claude/worktrees/agent-2",
        },
        {
          name: "agent-5",
          branch: "agent-5",
          dirty: 0,
          ageDays: 31,
          path: "/Users/zee/Code/argo/.claude/worktrees/agent-5",
        },
      ],
    },
  ],
}
